### ISSUE TITLE
[linter] does not compile with typescript 3.6.2

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#471]
```
src/rules/EndpointsAreAccessibleFromCache.ts:47:20 - error TS2488: Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator.

47       product.map(([xhrUrl, cacheSuffix]) =>
                      ~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```
