### PR TITLE
Upgrade to Typescript 3.6.2

### LINKED ISSUE #471: [linter] does not compile with typescript 3.6.2
```
src/rules/EndpointsAreAccessibleFromCache.ts:47:20 - error TS2488: Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator.

47       product.map(([xhrUrl, cacheSuffix]) =>
                      ~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

### PR DESCRIPTION
**Pull request by ithinkihaveacat**
Add some missing types that 3.6.2 catches. Fixes #471.

### CODE REVIEW

**Comment by ithinkihaveacat** [comment]
@sebastianbenz Would you be able to look at this? A fairly straightforward one!
